import {countDown, schedule} from "../src"

test("should count down", async () => {
  const c = countDown(2)
  const c2 = await c.next()
  expect(c2.value).toBe("Getting ready: 2")
  expect(c2.done).toBe(false)
  const c1 = await c.next()
  expect(c1.value).toBe("Getting ready: 1")
  expect(c2.done).toBe(false)
  const c0 = await c.next()
  expect(c0.value).toBe("GO")
  expect(c0.done).toBe(true)
})
test("should return error: not team evey bar", async () => {
  const s = schedule(3, 2, 4)
  const s1 = await s.next()
  expect(s1.value.error).toBe("There needs to be at least one team per bar!")
  expect(s1.done).toBe(true)
})
test("should return error: too many teams", async () => {
  const s = schedule(3, 7, 4)
  const s1 = await s.next()
  expect(s1.value.error).toBe("Only a maximum of two teams per bar is supported!")
  expect(s1.done).toBe(true)
})
test("should return error: odd number of matches", async () => {
  const s = schedule(3, 3, 3)
  const s1 = await s.next()
  expect(s1.value.error).toBe("Please choose an even number of matches!")
  expect(s1.done).toBe(true)
})
test("should return schedule for 2 teams in 2 bars for 2 games", async () => {
  const s = schedule(2, 2, 2)
  const s1 = await s.next()
  expect(s1.value.bars.count).toBe(2)
  expect(s1.value.teams.count).toBe(2)
  expect(s1.value.completed).toBe(false)
  expect(s1.value.error).toBe("")
  expect(s1.value.message).toBe("")
  expect(s1.done).toBe(false)
  const s2 = await s.next()
  expect(s2.value.completed).toBe(true)
})
test("should return schedule for 3 teams in 2 bars for 4 games", async () => {
  const s = schedule(2, 2, 2)
  const s1 = await s.next()
  // first yield is not yet the schedule calculation
  expect(s1.value.completed).toBe(false)
  expect(s1.value.error).toBe("")
  expect(s1.value.message).toBe("")
  expect(s1.done).toBe(false)
  const s2 = await s.next()
  expect(s2.value.completed).toBe(true)
})
